# Site settings
title           : limitedWish.org
email           : Ender Dai <ender.dai@gmail.com>
description     : "A limited wish lets you create nearly any type of effect."
baseurl         : ""
url             : "http://git.limitedwish.org"
twitter_username: EnderDai
github_username : xdai

# Build settings
markdown        : kramdown
permalink       : pretty

include:
  - _javascript

gems:
  - jekyll-paginate
  - jekyll-gist

# pagination
paginate: 5

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ender Dai"

