# Site settings
title: limitedWish.org
email: ender.dai@gmail.com
description: "A limited wish lets you create nearly any type of effect."
baseurl: ""
url: "http://git.limitedwish.org"
twitter_username: EnderDai
github_username:  xdai

# Build settings
markdown: kramdown
permalink: pretty
